---
api_url: http://localhost:8992
api_auth_enabled: true
ignore_tls_verification: false
log_level: INFO

redis_host: localhost
redis_port: 6379
redis_db: 0

session_cookie_path: /
session_cookie_secure: false
